package com.cafromet.modelodto;
// Generated 22 ene. 2021 19:54:49 by Hibernate Tools 5.4.21.Final

import com.cafromet.modelo.CentroMeteorologico;


/**
 * Medicion generated by hbm2java
 */
public class MedicionDTO implements java.io.Serializable {

	private int id;
	private String centroMeteorologico;
	private Integer dirViento;
	private Integer HRelativa;
	private Float PAtmosferica;
	private Float precip;
	private Float radSolar;
	private Float tempAmbiente;
	private Float VViento;
	private String ica;

	public MedicionDTO() {
	}

	public MedicionDTO(int id, String centroMeteorologico) {
		this.id = id;
		this.centroMeteorologico = centroMeteorologico;
	}

	public MedicionDTO(int id, String centroMeteorologico, Integer dirViento, Integer HRelativa,
					   Float PAtmosferica, Float precip, Float radSolar, Float tempAmbiente, Float VViento, String ica) {
		this.id = id;
		this.centroMeteorologico = centroMeteorologico;
		this.dirViento = dirViento;
		this.HRelativa = HRelativa;
		this.PAtmosferica = PAtmosferica;
		this.precip = precip;
		this.radSolar = radSolar;
		this.tempAmbiente = tempAmbiente;
		this.VViento = VViento;
		this.ica = ica;
	}


	public Integer getDirViento() {
		return this.dirViento;
	}

	public void setDirViento(Integer dirViento) {
		this.dirViento = dirViento;
	}

	public Integer getHRelativa() {
		return this.HRelativa;
	}

	public void setHRelativa(Integer HRelativa) {
		this.HRelativa = HRelativa;
	}

	public Float getPAtmosferica() {
		return this.PAtmosferica;
	}

	public void setPAtmosferica(Float PAtmosferica) {
		this.PAtmosferica = PAtmosferica;
	}

	public Float getPrecip() {
		return this.precip;
	}

	public void setPrecip(Float precip) {
		this.precip = precip;
	}

	public Float getRadSolar() {
		return this.radSolar;
	}

	public void setRadSolar(Float radSolar) {
		this.radSolar = radSolar;
	}

	public Float getTempAmbiente() {
		return this.tempAmbiente;
	}

	public void setTempAmbiente(Float tempAmbiente) {
		this.tempAmbiente = tempAmbiente;
	}

	public Float getVViento() {
		return this.VViento;
	}

	public void setVViento(Float VViento) {
		this.VViento = VViento;
	}

	public String getIca() {
		return this.ica;
	}

	public void setIca(String ica) {
		this.ica = ica;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCentroMeteorologico() {
		return centroMeteorologico;
	}

	public void setCentroMeteorologico(String centroMeteorologico) {
		this.centroMeteorologico = centroMeteorologico;
	}

}
