package com.cafromet.modelo;

import java.util.Collection;
import java.util.Iterator;
import java.util.Set;

// Generated 18 dic. 2020 7:16:02 by Hibernate Tools 5.4.21.Final

/**
 * CentrosMeteorologicos generated by hbm2java
 */
public class CentrosMeteorologicos implements java.io.Serializable {

	private int idCentroMet;
	private Municipios municipios;
	private String nombre;
	private String direccion;
	private Float latitud;
	private Float longitud;

	public CentrosMeteorologicos() {
	}

	public CentrosMeteorologicos(int idCentroMet, Municipios municipios) {
		this.idCentroMet = idCentroMet;
		this.municipios = municipios;
	}

	public CentrosMeteorologicos(int idCentroMet, Municipios municipios, String nombre, String direccion, Float latitud,
			Float longitud) {
		this.idCentroMet = idCentroMet;
		this.municipios = municipios;
		this.nombre = nombre;
		this.direccion = direccion;
		this.latitud = latitud;
		this.longitud = longitud;
	}

	public int getIdCentroMet() {
		return this.idCentroMet;
	}

	public void setIdCentroMet(int idCentroMet) {
		this.idCentroMet = idCentroMet;
	}

	public Municipios getMunicipios() {
		return this.municipios;
	}

	public void setMunicipios(Municipios municipios) {
		this.municipios = municipios;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public Float getLatitud() {
		return this.latitud;
	}

	public void setLatitud(Float latitud) {
		this.latitud = latitud;
	}

	public Float getLongitud() {
		return this.longitud;
	}

	public void setLongitud(Float longitud) {
		this.longitud = longitud;
	}
}
