package com.cafromet.modelo;
// Generated 24 dic. 2020 7:35:16 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

/**
 * CentrosMeteorologicos generated by hbm2java
 */
public class CentrosMeteorologicos implements java.io.Serializable {

	private int idCentroMet;
	private Municipios municipios;
	private String nombre;
	private String direccion;
	private Float latitud;
	private Float longitud;
	private Set medicionesCentroMets = new HashSet(0);

	public CentrosMeteorologicos() {
	}

	public CentrosMeteorologicos(int idCentroMet) {
		this.idCentroMet = idCentroMet;
	}

	public CentrosMeteorologicos(int idCentroMet, Municipios municipios, String nombre, String direccion, Float latitud,
			Float longitud, Set medicionesCentroMets) {
		this.idCentroMet = idCentroMet;
		this.municipios = municipios;
		this.nombre = nombre;
		this.direccion = direccion;
		this.latitud = latitud;
		this.longitud = longitud;
		this.medicionesCentroMets = medicionesCentroMets;
	}

	public int getIdCentroMet() {
		return this.idCentroMet;
	}

	public void setIdCentroMet(int idCentroMet) {
		this.idCentroMet = idCentroMet;
	}

	public Municipios getMunicipios() {
		return this.municipios;
	}

	public void setMunicipios(Municipios municipios) {
		this.municipios = municipios;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public Float getLatitud() {
		return this.latitud;
	}

	public void setLatitud(Float latitud) {
		this.latitud = latitud;
	}

	public Float getLongitud() {
		return this.longitud;
	}

	public void setLongitud(Float longitud) {
		this.longitud = longitud;
	}

	public Set getMedicionesCentroMets() {
		return this.medicionesCentroMets;
	}

	public void setMedicionesCentroMets(Set medicionesCentroMets) {
		this.medicionesCentroMets = medicionesCentroMets;
	}

}
