package com.cafromet.modelo;
// Generated 18 dic. 2020 7:16:02 by Hibernate Tools 5.4.21.Final

/**
 * Clientes generated by hbm2java
 */
public class Clientes implements java.io.Serializable {

	private int idCliente;
	private String usuario;
	private String passwd;

	public Clientes() {
	}

	public Clientes(int idCliente) {
		this.idCliente = idCliente;
	}

	public Clientes(int idCliente, String usuario, String passwd) {
		this.idCliente = idCliente;
		this.usuario = usuario;
		this.passwd = passwd;
	}

	public int getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(int idCliente) {
		this.idCliente = idCliente;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getPasswd() {
		return this.passwd;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

}
