package com.cafromet.modelo;
// Generated 27 dic. 2020 22:44:50 by Hibernate Tools 5.4.21.Final

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8909415821526613683L;
	private int idCliente;
	private String usuario;
	private String passwd;

	public Cliente() {
	}

	public Cliente(int idCliente) {
		this.idCliente = idCliente;
	}

	public Cliente(int idCliente, String usuario, String passwd) {
		this.idCliente = idCliente;
		this.usuario = usuario;
		this.passwd = passwd;
	}

	public int getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(int idCliente) {
		this.idCliente = idCliente;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getPasswd() {
		return this.passwd;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

}
