package com.cafromet.modelo;
// Generated 19 dic. 2020 1:10:31 by Hibernate Tools 5.4.18.Final

/**
 * EspaciosNaturales generated by hbm2java
 */
public class EspaciosNaturales implements java.io.Serializable {

	private int idEspacio;
	private String nombre;
	private String descripcion;
	private String tipo;
	private String direccion;
	private String categoria;
	private Float latitud;
	private Float longitud;

	public EspaciosNaturales() {
	}

	public EspaciosNaturales(int idEspacio) {
		this.idEspacio = idEspacio;
	}

	public EspaciosNaturales(int idEspacio, String nombre, String descripcion, String tipo, String direccion,
			String categoria, Float latitud, Float longitud) {
		this.idEspacio = idEspacio;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.tipo = tipo;
		this.direccion = direccion;
		this.categoria = categoria;
		this.latitud = latitud;
		this.longitud = longitud;
	}

	public int getIdEspacio() {
		return this.idEspacio;
	}

	public void setIdEspacio(int idEspacio) {
		this.idEspacio = idEspacio;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	public Float getLatitud() {
		return this.latitud;
	}

	public void setLatitud(Float latitud) {
		this.latitud = latitud;
	}

	public Float getLongitud() {
		return this.longitud;
	}

	public void setLongitud(Float longitud) {
		this.longitud = longitud;
	}

}
