package com.cafromet.modelo;
// Generated 26 ene. 2021 4:12:22 by Hibernate Tools 5.4.21.Final

/**
 * Fotos generated by hbm2java
 */
public class Fotos implements java.io.Serializable {

	private String idFoto;
	private Cliente cliente;
	private EspacioNatural espacioNatural;

	public Fotos() {
	}

	public Fotos(String idFoto) {
		this.idFoto = idFoto;
	}

	public Fotos(String idFoto, Cliente cliente, EspacioNatural espacioNatural) {
		this.idFoto = idFoto;
		this.cliente = cliente;
		this.espacioNatural = espacioNatural;
	}

	public String getIdFoto() {
		return this.idFoto;
	}

	public void setIdFoto(String idFoto) {
		this.idFoto = idFoto;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public EspacioNatural getEspacioNatural() {
		return this.espacioNatural;
	}

	public void setEspacioNatural(EspacioNatural espacioNatural) {
		this.espacioNatural = espacioNatural;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idFoto == null) ? 0 : idFoto.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Fotos other = (Fotos) obj;
		if (idFoto == null) {
			if (other.idFoto != null)
				return false;
		} else if (!idFoto.equals(other.idFoto))
			return false;
		return true;
	}

}
