package com.cafromet.modelo;
// Generated 18 dic. 2020 7:16:02 by Hibernate Tools 5.4.21.Final

/**
 * Fuentes generated by hbm2java
 */
public class Fuentes implements java.io.Serializable {

	private int idIndex;
	private String formato;
	private String nombre;
	private String url;
	private String hash;

	public Fuentes() {
	}

	public Fuentes(int idIndex) {
		this.idIndex = idIndex;
	}

	public Fuentes(int idIndex, String formato, String nombre, String url, String hash) {
		this.idIndex = idIndex;
		this.formato = formato;
		this.nombre = nombre;
		this.url = url;
		this.hash = hash;
	}

	public int getIdIndex() {
		return this.idIndex;
	}

	public void setIdIndex(int idIndex) {
		this.idIndex = idIndex;
	}

	public String getFormato() {
		return this.formato;
	}

	public void setFormato(String formato) {
		this.formato = formato;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getHash() {
		return this.hash;
	}

	public void setHash(String hash) {
		this.hash = hash;
	}

}
