package com.cafromet.modelo;
// Generated 22 ene. 2021 19:54:49 by Hibernate Tools 5.4.21.Final

/**
 * Medicion generated by hbm2java
 */
public class Medicion implements java.io.Serializable {

	private MedicionId id;
	private CentroMeteorologico centroMeteorologico;
	private Integer dirViento;
	private Integer HRelativa;
	private Float PAtmosferica;
	private Float precip;
	private Float radSolar;
	private Float tempAmbiente;
	private Float VViento;
	private String ica;

	public Medicion() {
		this.id = new MedicionId();
	}

	public Medicion(MedicionId id, CentroMeteorologico centroMeteorologico) {
		this.id = id;
		this.centroMeteorologico = centroMeteorologico;
	}

	public Medicion(MedicionId id, CentroMeteorologico centroMeteorologico, Integer dirViento, Integer HRelativa,
			Float PAtmosferica, Float precip, Float radSolar, Float tempAmbiente, Float VViento, String ica) {
		this.id = id;
		this.centroMeteorologico = centroMeteorologico;
		this.dirViento = dirViento;
		this.HRelativa = HRelativa;
		this.PAtmosferica = PAtmosferica;
		this.precip = precip;
		this.radSolar = radSolar;
		this.tempAmbiente = tempAmbiente;
		this.VViento = VViento;
		this.ica = ica;
	}

	public MedicionId getId() {
		return this.id;
	}

	public void setId(MedicionId id) {
		this.id = id;
	}

	public CentroMeteorologico getCentroMeteorologico() {
		return this.centroMeteorologico;
	}

	public void setCentroMeteorologico(CentroMeteorologico centroMeteorologico) {
		this.centroMeteorologico = centroMeteorologico;
	}

	public Integer getDirViento() {
		return this.dirViento;
	}

	public void setDirViento(Integer dirViento) {
		this.dirViento = dirViento;
	}

	public Integer getHRelativa() {
		return this.HRelativa;
	}

	public void setHRelativa(Integer HRelativa) {
		this.HRelativa = HRelativa;
	}

	public Float getPAtmosferica() {
		return this.PAtmosferica;
	}

	public void setPAtmosferica(Float PAtmosferica) {
		this.PAtmosferica = PAtmosferica;
	}

	public Float getPrecip() {
		return this.precip;
	}

	public void setPrecip(Float precip) {
		this.precip = precip;
	}

	public Float getRadSolar() {
		return this.radSolar;
	}

	public void setRadSolar(Float radSolar) {
		this.radSolar = radSolar;
	}

	public Float getTempAmbiente() {
		return this.tempAmbiente;
	}

	public void setTempAmbiente(Float tempAmbiente) {
		this.tempAmbiente = tempAmbiente;
	}

	public Float getVViento() {
		return this.VViento;
	}

	public void setVViento(Float VViento) {
		this.VViento = VViento;
	}

	public String getIca() {
		return this.ica;
	}

	public void setIca(String ica) {
		this.ica = ica;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Medicion other = (Medicion) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}
	
	@Override
	public String toString() {
		return "ID CENTRO = " + id.getIdCentroMet() + " || FECHA = " + id.getFecha() + " || HORA = " + id.getHora();
		
	}
}
