package com.cafromet.modelo;
// Generated 4 ene. 2021 19:38:01 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Municipio generated by hbm2java
 */
public class Municipio implements java.io.Serializable {

	private int idMunicipio;
	private Provincia provincia;
	private String nombre;
	private Set municipio_EspacioNaturals = new HashSet(0);
	private Set centroMeteorologicos = new HashSet(0);

	public Municipio() {
	}

	public Municipio(int idMunicipio) {
		this.idMunicipio = idMunicipio;
	}

	public Municipio(int idMunicipio, Provincia provincia, String nombre, Set municipio_EspacioNaturals,
			Set centroMeteorologicos) {
		this.idMunicipio = idMunicipio;
		this.provincia = provincia;
		this.nombre = nombre;
		this.municipio_EspacioNaturals = municipio_EspacioNaturals;
		this.centroMeteorologicos = centroMeteorologicos;
	}

	public int getIdMunicipio() {
		return this.idMunicipio;
	}

	public void setIdMunicipio(int idMunicipio) {
		this.idMunicipio = idMunicipio;
	}

	public Provincia getProvincia() {
		return this.provincia;
	}

	public void setProvincia(Provincia provincia) {
		this.provincia = provincia;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getMunicipio_EspacioNaturals() {
		return this.municipio_EspacioNaturals;
	}

	public void setMunicipio_EspacioNaturals(Set municipio_EspacioNaturals) {
		this.municipio_EspacioNaturals = municipio_EspacioNaturals;
	}

	public Set getCentroMeteorologicos() {
		return this.centroMeteorologicos;
	}

	public void setCentroMeteorologicos(Set centroMeteorologicos) {
		this.centroMeteorologicos = centroMeteorologicos;
	}

}
