package com.cafromet.modelo;
// Generated 18 dic. 2020 7:16:02 by Hibernate Tools 5.4.21.Final

/**
 * Provincias generated by hbm2java
 */
public class Provincias implements java.io.Serializable {

	private int idProvincia;
	private String nombre;

	public Provincias() {
	}

	public Provincias(int idProvincia) {
		this.idProvincia = idProvincia;
	}

	public Provincias(int idProvincia, String nombre) {
		this.idProvincia = idProvincia;
		this.nombre = nombre;
	}

	public int getIdProvincia() {
		return this.idProvincia;
	}

	public void setIdProvincia(int idProvincia) {
		this.idProvincia = idProvincia;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
