package com.cafromet.modelo;
// Generated 24 dic. 2020 7:35:16 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Provincias generated by hbm2java
 */
public class Provincias implements java.io.Serializable {

	private int idProvincia;
	private String nombre;
	private Set municipioses = new HashSet(0);

	public Provincias() {
	}

	public Provincias(int idProvincia) {
		this.idProvincia = idProvincia;
	}

	public Provincias(int idProvincia, String nombre, Set municipioses) {
		this.idProvincia = idProvincia;
		this.nombre = nombre;
		this.municipioses = municipioses;
	}

	public int getIdProvincia() {
		return this.idProvincia;
	}

	public void setIdProvincia(int idProvincia) {
		this.idProvincia = idProvincia;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getMunicipioses() {
		return this.municipioses;
	}

	public void setMunicipioses(Set municipioses) {
		this.municipioses = municipioses;
	}

}
