package modeloDTO;
// Generated 11 ene. 2021 5:03:03 by Hibernate Tools 5.4.21.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;

/**
 * Municipio generated by hbm2java
 */
public class MunicipioDTO implements java.io.Serializable {

	private Integer idMunicipio;
	private String nombre;
	
	public MunicipioDTO() {
		
	}

	public Integer getIdMunicipio() {
		return idMunicipio;
	}

	public void setIdMunicipio(Integer idMunicipio) {
		this.idMunicipio = idMunicipio;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}


}


